Feat/coverage
tasking/firebase-app pull request #2
Opened 2017-08-23 13:52 UTC by alisson446

2017-08-25 22:47 UTC, georgesboris requested changes
Explica a necessidade dessa lógica mais acoplada aí.

2017-08-25 22:47 UTC, georgesboris commented on index.js
> +		} = generateRules(config, logOwners, getLogPath, commandSource);
@alisson446 por quê o coverage tem que depender dos arquivos que estão gerando as rules? pq tendo o `config` você já tem todas as informações de separação de path/action/owner. eu tinha separado a lógica justamente por isso... o coverage é independente de como o usuário define as regras dele.

2017-08-25 23:04 UTC, georgesboris commented on src/rules/utils/checkRulesCoverage.js
> +    covered += getPathsWithRules(owners, fileRules);
@alisson isso tá simplificado demais e não dá um resultado real... pra checar uma action vc tem q checar se o log criado por ela tem regra de escrita e pra checar um owner vc tem q ver se o conjunto de logs dele tem regra de leitura. pra isso não precisa nem um pouco das regras separadas em arquivo. Desacopla isso ai.

2017-08-26 01:17 UTC, Alisson commented on src/rules/utils/checkRulesCoverage.js
> +    covered += getPathsWithRules(owners, fileRules);
Você marcou o Alisson errado.

2017-10-11 18:37 UTC, closed without merging